# In seconds
interval: 30
# Do you want to remove the mobs?
deleteMobs: false
# Do you want to remove the animals?
deleteAnimals: false
# Do you want to remove the projectiles?
deleteProjectile: false
# Do you want to remove the experience orbs ?
deleteExpOrb: false
